-- AlterTable
ALTER TABLE `Customer` MODIFY `following_count` INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `Post` MODIFY `post_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `update_at` DATETIME(3) NOT NULL;

-- AlterTable
ALTER TABLE `User` MODIFY `craete_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
